// <auto-generated />
using System;
using GalaxyUML.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalaxyUML.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GalaxyUML.Data.Entities.BannedUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ChatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ClassAttributeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassBoxId");

                    b.ToTable("ClassAttributes");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ClassMethodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassBoxId");

                    b.ToTable("ClassMethods");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DiagramElementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ObjectType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("X1")
                        .HasColumnType("float");

                    b.Property<double>("X2")
                        .HasColumnType("float");

                    b.Property<double>("Y1")
                        .HasColumnType("float");

                    b.Property<double>("Y2")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("DiagramElements", (string)null);

                    b.HasDiscriminator<int>("ObjectType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndingTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BoardId")
                        .IsUnique();

                    b.HasIndex("OrganizedById");

                    b.HasIndex("TeamId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanDraw")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("MeetingId", "TeamMemberId")
                        .IsUnique();

                    b.ToTable("MeetingParticipants");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentMeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.BoxEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.DiagramElementEntity");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DiagramEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.DiagramElementEntity");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("MeetingId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.LineEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.DiagramElementEntity");

                    b.Property<Guid>("EndBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MiddleText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StartBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text2")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EndBoxId");

                    b.HasIndex("StartBoxId");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TextEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.DiagramElementEntity");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ClassBoxEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.BoxEntity");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.BannedUserEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.TeamEntity", "Team")
                        .WithMany("BannedUsers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ChatEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.MeetingEntity", "Meeting")
                        .WithOne("Chat")
                        .HasForeignKey("GalaxyUML.Data.Entities.ChatEntity", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ClassAttributeEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.ClassBoxEntity", "ClassBox")
                        .WithMany("Attributes")
                        .HasForeignKey("ClassBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassBox");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ClassMethodEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.ClassBoxEntity", "ClassBox")
                        .WithMany("Methods")
                        .HasForeignKey("ClassBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassBox");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DiagramElementEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.DiagramElementEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.DiagramElementEntity", "Board")
                        .WithOne()
                        .HasForeignKey("GalaxyUML.Data.Entities.MeetingEntity", "BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.TeamMemberEntity", "OrganizedBy")
                        .WithMany()
                        .HasForeignKey("OrganizedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.TeamEntity", "Team")
                        .WithMany("Meetings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("OrganizedBy");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingParticipantEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.MeetingEntity", "Meeting")
                        .WithMany("Participants")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.TeamMemberEntity", "TeamMember")
                        .WithMany("Meetings")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.ChatEntity", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.UserEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamMemberEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.TeamEntity", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DiagramEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.MeetingEntity", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.LineEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.BoxEntity", "EndBox")
                        .WithMany("Incoming")
                        .HasForeignKey("EndBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.BoxEntity", "StartBox")
                        .WithMany("Outgoing")
                        .HasForeignKey("StartBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EndBox");

                    b.Navigation("StartBox");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ChatEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DiagramElementEntity", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingEntity", b =>
                {
                    b.Navigation("Chat")
                        .IsRequired();

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamEntity", b =>
                {
                    b.Navigation("BannedUsers");

                    b.Navigation("Meetings");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamMemberEntity", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.BoxEntity", b =>
                {
                    b.Navigation("Incoming");

                    b.Navigation("Outgoing");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ClassBoxEntity", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Methods");
                });
#pragma warning restore 612, 618
        }
    }
}
