// <auto-generated />
using System;
using GalaxyUML.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalaxyUML.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212091009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GalaxyUML.Data.Entities.AttributeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdClassBox")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdClassBox");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.BannedUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdTeam");

                    b.HasIndex("IdUser", "IdTeam")
                        .IsUnique();

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ChatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMeeting")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdMeeting")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DiagramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("EndX")
                        .HasColumnType("int");

                    b.Property<int>("EndY")
                        .HasColumnType("int");

                    b.Property<Guid>("IdMeeting")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdParent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StartX")
                        .HasColumnType("int");

                    b.Property<int>("StartY")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMeeting")
                        .IsUnique();

                    b.HasIndex("IdParent");

                    b.ToTable("Diagrams");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DiagramEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndingTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdBoard")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdOrganizer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TeamEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdOrganizer");

                    b.HasIndex("TeamEntityId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMeeting")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdParticipant")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdMeeting");

                    b.HasIndex("IdParticipant");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSender")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdSender");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MethodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdClassBox")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdClassBox");

                    b.ToTable("Methods");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeamOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdTeamOwner");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMember")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("TextEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdMember");

                    b.HasIndex("TextEntityId");

                    b.HasIndex("IdTeam", "IdMember")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DrawableEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.DiagramEntity");

                    b.HasDiscriminator().HasValue("DrawableEntity");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.BoxEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.DrawableEntity");

                    b.HasDiscriminator().HasValue("BoxEntity");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.LineEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.DrawableEntity");

                    b.Property<Guid>("IdBox1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdBox2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MiddleText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("IdBox1");

                    b.HasIndex("IdBox2");

                    b.HasDiscriminator().HasValue("LineEntity");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TextEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.DrawableEntity");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("TextEntity");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ClassBoxEntity", b =>
                {
                    b.HasBaseType("GalaxyUML.Data.Entities.BoxEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stereotype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TextSize")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("ClassBoxEntity");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.AttributeEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.ClassBoxEntity", "ClassBox")
                        .WithMany("Attributes")
                        .HasForeignKey("IdClassBox")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassBox");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.BannedUserEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.TeamEntity", "Team")
                        .WithMany("BannedUsers")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.UserEntity", "User")
                        .WithMany("BannedTeams")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ChatEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.MeetingEntity", "Meeting")
                        .WithOne("Chat")
                        .HasForeignKey("GalaxyUML.Data.Entities.ChatEntity", "IdMeeting")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DiagramEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.MeetingEntity", "Meeting")
                        .WithOne("Board")
                        .HasForeignKey("GalaxyUML.Data.Entities.DiagramEntity", "IdMeeting")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.DiagramEntity", "Parent")
                        .WithMany("Objects")
                        .HasForeignKey("IdParent")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.MeetingParticipantEntity", "Organizer")
                        .WithMany()
                        .HasForeignKey("IdOrganizer")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.TeamEntity", null)
                        .WithMany("Meetings")
                        .HasForeignKey("TeamEntityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingParticipantEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.MeetingEntity", "Meeting")
                        .WithMany("Participants")
                        .HasForeignKey("IdMeeting")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.TeamMemberEntity", "Participant")
                        .WithMany("Meetings")
                        .HasForeignKey("IdParticipant")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.ChatEntity", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.MeetingParticipantEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("IdSender")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MethodEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.ClassBoxEntity", "ClassBox")
                        .WithMany("Methods")
                        .HasForeignKey("IdClassBox")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassBox");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.TeamMemberEntity", "TeamOwner")
                        .WithMany()
                        .HasForeignKey("IdTeamOwner")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TeamOwner");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamMemberEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.UserEntity", "Member")
                        .WithMany("Teams")
                        .HasForeignKey("IdMember")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.TeamEntity", "Team")
                        .WithMany("Members")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.TextEntity", null)
                        .WithMany("TeamMembers")
                        .HasForeignKey("TextEntityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.LineEntity", b =>
                {
                    b.HasOne("GalaxyUML.Data.Entities.BoxEntity", "Box1")
                        .WithMany("LinesAsStart")
                        .HasForeignKey("IdBox1")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GalaxyUML.Data.Entities.BoxEntity", "Box2")
                        .WithMany("LinesAsEnd")
                        .HasForeignKey("IdBox2")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Box1");

                    b.Navigation("Box2");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ChatEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.DiagramEntity", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.MeetingEntity", b =>
                {
                    b.Navigation("Board")
                        .IsRequired();

                    b.Navigation("Chat")
                        .IsRequired();

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamEntity", b =>
                {
                    b.Navigation("BannedUsers");

                    b.Navigation("Meetings");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TeamMemberEntity", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("BannedTeams");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.BoxEntity", b =>
                {
                    b.Navigation("LinesAsEnd");

                    b.Navigation("LinesAsStart");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.TextEntity", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("GalaxyUML.Data.Entities.ClassBoxEntity", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Methods");
                });
#pragma warning restore 612, 618
        }
    }
}
